# Welcome to Jekyll!

# Site settings
title: CodeRoad
description: |
  Interactive Coding Tutorials in your Editor
owner: Shawn McKay
first_published: 2016
email: coderoad-app@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://coderoad.github.com
social:
  twitter: https://twitter.com/coderoadapp
  github: https://github.com/coderoad
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/114957986906029613694/about
  email: mailto:coderoadapp@gmail.com?subject=CodeRoad
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCDDw5bc8muROZkT3IUqamPg
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  default_lang: js
#sass:
#  style: compressed
